spring:
  application:
    name: bework-authorization

server:
  port: 9001
  context-path: /bework-authorization
  use-forward-headers: false

eureka:
  instance:
      hostname: localhost
      port: 9010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG

