spring:
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
    #      location: C:/Users/VuTrinh/AppData/Local/Temp
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: bework-livestream-service

server:
  port: 9700
  tomcat:
    uri-endcode: UTF-8

eureka:
  instance:
    hostname: localhost
    port: 9010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue: "beedu@2019"
      id: fooScope
      service-id: ${PREFIX:}resource