spring:
  application:
    name: bework-worker

#eureka:
#  instance:
#      hostname: localhost
#      port: 9010
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/